- hosts: vm
  gather_facts: False
  remote_user: ramu
  become: yes
  
  vars: 
    mysql_root_password: test
 
  tasks:
    - name: Apt update
      apt: update_cache=yes
    - name: Install Mysql
      apt: name={{ item }} state=present
      with_items: 
        - python-mysqldb
        - mysql-server
#    - name: update mysql root password for all root accounts
#      mysql_user: 
#        name: root 
#        host: "{{ item }}" 
#        password: "{{ mysql_root_password }}" 
#        priv: "*.*:ALL,GRANT"
#      with_items:
#        - "{{ vm_host }}"
#        - 127.0.0.1
#        - ::1
#        - localhost
    - name: Copy the root credentials as .my.cnf file
      template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
    - name: create database
      mysql_user:
        login_user: root
        login_password: test
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
    - name: Create DB
      mysql_db: name=db1 state=present 
